version : '2'
services:
  web:
    container_name: nginx
    image: nginx:latest
    volumes:
     - .:/var/www/html/contactos/
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
    depends_on:
     - php
    networks:
      public-network:
  php:
    build:
      context: ./php
    container_name: php
    image: php:7-fpm
    tty: true
    volumes:
      - .:/var/www/html/contactos/  
    expose:
    - "9000"
    ports:
        - "9000:9000"
    networks:
      public-network:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    volumes:
      - "db-postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      public-network:
networks:
  public-network:
    driver: bridge

volumes:
  db-postgres: